import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Inter } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from 'next/link';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${inter.variable}`}>
        <header style={{
          width: '100%',
          background: '#fff',
          borderBottom: '1px solid #e3eaf2',
          padding: '1.1rem 0',
          marginBottom: 32,
          boxShadow: '0 2px 8px #f6fafd',
        }}>
          <nav style={{
            maxWidth: 1100,
            margin: '0 auto',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: 24,
            padding: '0 1.5rem',
          }}>
            <Link href="/" style={{ fontWeight: 700, fontSize: '1.35rem', color: '#1a73e8', textDecoration: 'none', letterSpacing: 1 }}>Get It Fixed</Link>
            <div style={{ display: 'flex', gap: 24, alignItems: 'center' }}>
              <Link href="/about" style={{ color: '#2d3a4a', textDecoration: 'none', fontWeight: 500 }}>About</Link>
              <Link href="/services/computer-laptop-troubleshooting" style={{ color: '#2d3a4a', textDecoration: 'none', fontWeight: 500 }}>Services</Link>
              <Link href="/contact" style={{ color: '#2d3a4a', textDecoration: 'none', fontWeight: 500 }}>Contact</Link>

            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
